---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package on Ubuntu
    apt:
      name: apache2
    when: ansible_distribution == "Ubuntu"

  - name: install apache package on CentOS
    dnf:
      name: httpd
    when: ansible_distribution == "CentOS"      